name: Expense Automation Workflow

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Choose your desired runner platform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the Python version you want to use

    - name: Install Dependencies (if needed)
      run: pip install -r requirements.txt  # Install any required packages listed in requirements.txt

    - name: Run Python Script
      run: python main.py  # Adjust the path and name to your script
