name: Expense Automation Workflow

on:
  schedule:
    # Runs at 12:00 PM UTC every Monday
    # - cron: '0 12 * * 1'
  workflow_dispatch: # Allows manual triggering of the workflow


jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Choose your desired runner platform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Specify the Python version you want to use

    - name: Install Dependencies (if needed)
      run: pip install -r requirements.txt  # Install any required packages listed in requirements.txt

    - name: Setup GOOGLE TOKEN
      run: echo '${{ secrets.GOOGLE_AUTH }}' > token.json
      
    - name: Run Python Script
      env:
        STARLING_TOKEN: ${{ secrets.STARLING_TOKEN }}
      run: python main.py  # Adjust the path and name to your script
